services: 
  client:
    container_name: "client"
    build:
      context: .
      dockerfile: client/Dockerfile
    ports: 
      - "3000:3000"

  c2_db:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}" 
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: postgres:18.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - c2_pgdata:/var/lib/postgresql/data

  c2:
    depends_on:
      - c2_db
      - nginx
    build:
      context: .
      dockerfile: c2/Dockerfile
    environment:
      C2_PORT: "13371"
      C2_HOST: "0.0.0.0"
      POSTGRES_USER: "${POSTGRES_USER}" 
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "c2_db"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports: 
      - "13371:13371"
    volumes:
      - ./c2_data:/data

  nginx:
    image: nginx:latest
    ports: 
      - 443:443
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

volumes:
  c2_pgdata: