[target.x86_64-pc-windows-msvc]
rustflags = [
    "-Z", "location-detail=none",
    # "-Z", "fmt-debug=none",
    "-C", "panic=abort",
    # "-C", "link-arg=-s",
    # "-C", "link-arg=/DEBUG:NONE",
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=/MERGE:.rdata=.text",
    "-C", "link-arg=/MERGE:.pdata=.text",
    "-C", "inline-threshold=275",
]